[package]
name = "easy_shot_native"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures-util = "0.3"
gstreamer = "0.25.3"
tokio = { version = "1", features = ["rt", "macros", "time"] }
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }
